audta/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.static import serve
from main import views as general_views
from django.conf import settings
from registration.backends.default.views import RegistrationView
from users.forms import RegForm
from users.backend import user_created
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin', admin.site.urls),

    url(r'^', include('web.urls', namespace="web")),
    url(r'^app/$',general_views.app,name='app'),
    url(r'^report/$',general_views.report,name='report'),
    url(r'^app/dashboard/$',general_views.dashboard,name='dashboard'),
    url(r'^app/auditorium/', include('auditoriums.urls', namespace="auditoriums")),
    url(r'^app/partner/', include('partners.urls', namespace="partners")),
    url(r'^app/resrvation/', include('reservations.urls', namespace="reservations")),

    url(r'^app/accounts/register/$', RegistrationView.as_view(form_class=RegForm),name='registration_register'),
    url(r'^app/accounts/', include('registration.backends.default.urls')), 

    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT}),
]

reservations/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views


urlpatterns = [               
    url(r'^reservations/create/$',views.create_reservation,name='create_reservation'),
    url(r'^reservations/view/$',views.reservations,name='reservations'),
    url(r'^reservations/delete/(?P<pk>.*)/$',views.delete_reservation,name='delete_reservation'),
    url(r'^reservations/cancel/(?P<pk>.*)/$',views.cancel_reservation,name='cancel_reservation'),
    
]

web/urls.py
from django.conf.urls import url, include
import views

urlpatterns = [               

    url(r'^$', views.index,name='index'), 
   
    url(r'^single/(?P<pk>.*)/$', views.single,name='single'),
   	url(r'^customer-registration/$', views.customer_registration, name='customer_registration'), 
    url(r'^login/$', views.customer_login, name='customer_login'),
    url(r'^customer/logout/$', views.logout, name='logout'),

    url(r'^book-now/(?P<pk>.*)/$', views.book_now,name='book_now'),
    url(r'^booking-list/$', views.reservations, name='reservations'),
    url(r'^print-booking/(?P<pk>.*)/$', views.print_reservation,name='print_reservation'),
    url(r'^check-availabilty/$', views.check_availabilty, name='check_availabilty'), 
    
]

reservations/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.core.validators import MinValueValidator
from django.utils.translation import ugettext_lazy as _
from decimal import Decimal
from versatileimagefield.fields import VersatileImageField
from main.models import BaseModel

STATUS = (
    ('booked', 'Booked'),
    ('cancelled', 'Cancelled'),
    ('completed', 'Completed'),
)


class Reservation(BaseModel):
    auditorium = models.ForeignKey("auditoriums.Auditorium")
    customer = models.ForeignKey("customers.Customer",null=True,blank=True)
    from_date = models.DateTimeField()
    to_date = models.DateTimeField(null=True,blank=True) 
    client_name = models.CharField(max_length=256)
    client_address = models.CharField(max_length=128)
    city = models.CharField(max_length=128)
    zipcode = models.CharField(max_length=128)
    phone = models.CharField(max_length=128)
    email = models.EmailField(null=True,blank=True)
    amount = models.DecimalField(default=0.00,blank=True,decimal_places=2, max_digits=15, validators=[MinValueValidator(Decimal('0.00'))])
    is_deleted = models.BooleanField(default=False)
    status = models.CharField(max_length=128,choices=STATUS)

    class Meta:
        db_table = 'reservations'
        verbose_name = _('reservation')
        verbose_name_plural = _('reservations')
        ordering = ('id',)
        
    class Admin:
        list_display = ('id',)

    def __unicode__(self):
        return self.title

reservations/forms.py
from django.utils.translation import ugettext_lazy as _
from django import forms
from django.forms.widgets import TextInput,Textarea,Select,DateInput, CheckboxInput
from django.contrib.auth.models import User
from reservations.models import Reservation
from dal import autocomplete


class ReservationForm(forms.ModelForm):

	class Meta:
		model = Reservation
		exclude = ['creator','updator','auto_id','is_deleted','amount','customer','status']
		widgets = {
			'auditorium': autocomplete.ModelSelect2(url='auditoriums:auditorium_autocomplete', attrs={'data-placeholder': 'Auditorium', 'data-minimum-input-length': 1},), 
			'from_date': TextInput(attrs={'class': 'required form-control date-picker','placeholder' : 'From Date'}),
			'to_date': TextInput(attrs={'class': 'form-control date-picker','placeholder' : 'To Date'}),
			'client_name': TextInput(attrs={'class': 'required form-control','placeholder' : 'Name'}),
			'client_address': TextInput(attrs={'class': 'required form-control','placeholder' : 'Address'}),
			'city': TextInput(attrs={'class': 'required form-control','placeholder' : 'City'}),
			'zipcode': TextInput(attrs={'class': 'required form-control','placeholder' : 'ZIP'}),
			'phone': TextInput(attrs={'class': 'required form-control number','placeholder' : 'Phone'}),
			'email': TextInput(attrs={'class': 'required form-control','placeholder' : 'Email'}),
			
		}

		error_messages = {
			'name' : {
				'required' : _("Product field is required."),
			},
			'Address' : {
				'required' : _("Offer percentage field is required."),
			},
			'district' : {
				'required' : _("Start date field is required."),
			},
			'state' : {
				'required' : _("End Date field is required."),
			},
			'contact1' : {
				'required' : _("End Date field is required."),
			},
			'contact2' : {
				'required' : _("End Date field is required."),
			},
			'zipcode' : {
				'required' : _("End Date field is required."),
			},
		}

reservations/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render,get_object_or_404
from django.http.response import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from reservations.models import Reservation
from reservations.forms import ReservationForm
from django.contrib.auth.decorators import login_required
from main.decorators import check_mode,role_required
from main.functions import get_auto_id,generate_form_errors
import json
import datetime


# Create your views here.
@check_mode
@login_required
@role_required(['partner','superadmin','administrator'])
def create_reservation(request):

    if request.method == 'POST':
        form = ReservationForm(request.POST,request.FILES)
        
        if form.is_valid():


            data = form.save(commit=False)
            data.creator = request.user
            data.updator = request.user
            data.auto_id = get_auto_id(Reservation)
            data.status = 'booked'
            data.save() 

            response_data = {
                "status" : "true",
                "title" : "Successfully Created",
                "message" : "Reservation(s) created successfully.",
                "redirect" : "true",
                "redirect_url" : reverse('reservations:reservations')
            }

        else:
            message = generate_form_errors(form, formset=False)
            response_data = {
                "status" : "false",
                "stable" : "true",
                "title" : "Form validation error",
                "message" : message
            }   
        return HttpResponse(json.dumps(response_data), content_type='application/javascript')
    else:
        form = ReservationForm()

        context = {
            "title": "Create Reservation",
            "url": reverse('reservations:create_reservation'),
            "form" : form,
            "redirect" : True,

            "is_need_popup_box": True,
            "is_need_grid_system": True,
            "is_need_animations": True,
            "is_need_datetime_picker": True,
            "is_need_checkbox": True,
            "is_need_select_picker" : True,
            "is_need_formset" : True,
        }
        return render(request,'reservations/entry.html',context)


@check_mode
@login_required
@role_required(['partner','superadmin','administrator'])
def reservations(request):
    instances = Reservation.objects.filter(is_deleted=False)
    title = "reservations"

    query = request.GET.get("q")
    if query:
        instances = instances.filter(Q(name__icontains=query))
        title = "reservations - %s" % query

    context = {
        "instances": instances,
        'title': title,

        "is_need_popup_box": True,
        "is_need_grid_system": True,
        "is_need_animations": True,
        "is_need_datetime_picker": True,
        "is_need_checkbox": True
    }
    return render(request, 'reservations/reservations.html', context)


@check_mode
@login_required
@role_required(['partner','superadmin','administrator'])
def delete_reservation(request,pk):
    instance = get_object_or_404(Reservation.objects.filter(pk=pk,is_deleted=False))
    
    Reservation.objects.filter(pk=pk).update(is_deleted=True)
    
    response_data = {
        "status" : "true",
        "title" : "Successfully Deleted",
        "message" : "Reservation Successfully Deleted.",
        "redirect" : "true",
        "redirect_url" : reverse('reservations:reservations')
    }
    return HttpResponse(json.dumps(response_data), content_type='application/javascript')


@check_mode
@login_required
@role_required(['partner','superadmin','administrator'])
def cancel_reservation(request,pk):
    instance = get_object_or_404(Reservation.objects.filter(pk=pk,is_deleted=False))
    
    Reservation.objects.filter(pk=pk).update(status="cancelled")
    
    response_data = {
        "status" : "true",
        "title" : "Successfully Cancelled",
        "message" : "Reservation Successfully Cancelled.",
        "redirect" : "true",
        "redirect_url" : reverse('reservations:reservations')
    }
    return HttpResponse(json.dumps(response_data), content_type='application/javascript')

templates/web/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{% load static %}
		<meta charset="UTF-8">
		<title>Audito | Book your Venue now</title>
		<link rel="stylesheet" type="text/css" href="{% static 'web/css/fontello.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'web/css/style.css' %}" />
		<link href="{% static 'web/css/datepicker.min.css' %}" type="text/css" rel="stylesheet">
		<link rel="stylesheet" href="{% static 'web/css/sweetalert.css' %}" type="text/css" />
		<link rel="stylesheet" href="{% static 'web/css/owl.carousel.css' %}" type="text/css" />
		<link rel="stylesheet" href="{% static 'web/css/owl.theme.default.min.css' %}" type="text/css" />

		<script src="{% static 'web/js/jquery.min.js' %}"></script>
		<script src="{% static 'web/js/datepicker.min.js' %}"></script>
		<script src="{% static 'web/js/owl.carousel.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'web/js/sweetalert.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'web/js/jquery.validate.min.js' %}"></script>	
		<script type="text/javascript" src="{% static 'web/js/script.js' %}"></script>
	</head>
	<body>
		<section id="top">
			<header>
				<section class="wrapper">
					<h1>
						<a href="{% url 'web:index' %}">
							<img src="{% static 'web/images/logo.png' %}" alt="Logo" />
						</a>
					</h1>
					<nav class="left">
						<ul>
							<li><a href="{% url 'web:index' %}">Home</a></li>
							<li><a href="#">Contact</a></li>
							<li><a href="#">Privacy Policy</a></li>
						</ul>
					</nav>
					<nav class="user right">
						<i class="icon icon-user"></i>
						{% if not user or user.is_anonymous %}
						<a class="user-login" href="#"> Log In</a>
						{% else %}
						<a class="user-logout" href="{% url 'web:logout' %}"> Log Out</a>
						{% endif %}
					</nav>
					<br class="clear" />
				</section>
			</header>
			
		</section>
		{% block content %}

		{% endblock %}
		
				
			
		{% block static %}

		{% endblock %}
		{% include 'web/login.html' %}
		<footer>
			<section class="wrapper">
				<p>&copy;2019 Audto. All rights reserved.</p>
			</section>
		</footer>
		<script>
			$('.overlay').hide();
			$('.login.container').hide();
			$('[data-toggle="datepicker"]').datepicker({
				  startDate: "+0d",
				  format:'dd/mm/yyyy',
				  autoHide: 'True'
			});
			$('.datepicker').datepicker({
				  startDate: "+0d",
				  format:'dd/mm/yyyy',
				  autoHide: 'True'
			});
			
			$('[data-toggle="datepicker"]').datepicker({
				  startDate: "+0d",
				  format:'dd/mm/yyyy',
				  autoHide: 'True'
			});
			$(document).ready(function() {
				$('.overlay').hide();
				$('.login.container').show();
			});
			$('.user-login').on('click', function() {
			  $('.overlay').show();
			  $('.login.container').show();
			});
			$('.close-all').on('click', function() {
			  $('.overlay').hide();
			  $('.login.container').hide();
			});
			$('.toggle').on('click', function() {
			  $('.container').stop().addClass('active');
			  $('.container .login-card form').stop().removeClass('form');
			  $('.container .alt form').stop().addClass('form');
			});
			$('.alt .close').on('click', function() {
			  $('.container').stop().removeClass('active');
			  $('.container .login-card form').stop().addClass('form');
			  $('.container .alt form').stop().removeClass('form');
			});
		</script>
	</body>
</html>

templates/web/index.html

{% extends 'web/base.html' %}
{% block content %}
<section id="spotlight">
	<section class="wrapper">
		<h1>Book your Venue Now</h1>
		<div class="search">
			<form action="{% url 'web:index' %}" method="get">
				<div class="loc wid">
					<i class="icon icon-bank"></i><input type="text" name="slocation" placeholder="Location">
				</div>
				<div class="date wid">
					<i class="icon icon-calendar"></i><input type="text" data-toggle="datepicker" name="sdate" placeholder="Date">
				</div>
				<div class="but wid">
					<input type="submit" class=" button" value="Search Now" class="submit" />
				</div>
				<br class="clear" />
			</form>						
		</div>
	</section>
</section>
<section id="middle">
	<section class="wrapper">
		<section class="results">
			<ul class="cards left">
				{% for auditorium in auditoriums %}
				<li class="card left">
					<!-- <div class="offer">
						<span>50% <small>OFF</small></span>
					</div> -->
					<h4>{{auditorium.name}}</h4>
					<p>{{auditorium.title}}</p>
					<div class="price left">
						<h6>Price</h6>
						<i class="icon icon-diamond"></i><b>{{auditorium.rent}}</b>
					</div>
					<div class="rating right">
						<h6>Rating</h6>
						<i class="icon icon-star"></i>
						<i class="icon icon-star"></i>
						<i class="icon icon-star"></i>
						<i class="icon icon-star-empty"></i>
						<i class="icon icon-star-empty"></i>
					</div>
					<br class="clear">
					<a href="{% url 'web:single' pk=auditorium.pk %}" class="button">Book Now</a>
					
					
				</li>
				{% endfor %}
			</ul>
			<br class="clear" />
		</section>
		</section>
</section>
{% endblock %}
{% block static %}		
<script>
	$('[data-toggle="datepicker"]').datepicker({
		  startDate: "+0d",
		  format:'dd/mm/yyyy',
		  autoHide: 'True'
	});
</script>
{% endblock %}

templates/web/login.html
{% load static %}
<script type="text/javascript" src="{% static 'web/js/sweetalert.min.js' %}"></script>
<section class="overlay">
	<div class="close-all"></div>
	<div class="login container">
		<div class="card"></div>
		<div class="card login-card">
			<h1 class="title">Login</h1>
			{{form.non_field_errors}}
			<form class="ajax redirect reload form" action="{% url 'web:customer_login' %}" method="post">
				{% csrf_token %}
				<div class="input-container">
					<input type="text" id="#username" name="username">
					<label for="#username">Username</label>
					{% if form.username.errors %}
						<span class="error">{{ form.username.errors.as_text }}</span>
					{% endif %}
					<div class="bar"></div>
				</div>
				<div class="input-container">
					<input type="password" id="#password" name="password">
					<label for="#password">Password</label>
					{% if form.password.errors %}
						<span class="error">{{ form.password.errors.as_text }}</span>
					{% endif %}
					<div class="bar"></div>
				</div>
				<div class="button-container">
					<input type="submit" class=" button button1" value="Login" class="submit" />
				</div>
				<!-- <div class="footer"><a href="#">Forgot your password?</a></div> -->
			</form>
		</div>
		<div class="card alt">
			<div class="toggle icon icon-user"></i></div>
			<h1 class="title">Register
				<div class="close"></div>
			</h1>
			<form class="ajax redirect reload" action="{% url 'web:customer_registration' %}" method="post">
				{% csrf_token %} 
				<div class="input-container">
					<input type="text" id="id_username" name="username" >
					<label for="#id_username">Username</label>
					<div class="bar"></div>
				</div>
				<div class="input-container">
					<input type="email" id="id_email" name="email" >
					<label for="#id_username">E-mail</label>
					<div class="bar"></div>
				</div>
				<div class="input-container">
					<input type="password" id="id_password1" name="password1" >
					<label for="#id_password1">Password</label>
					<div class="bar"></div>
				</div>
				<div class="input-container">
					<input type="password" id="id_password2" name="password2" >
					<label for="#id_password2">Retype password</label>
					<div class="bar"></div>
				</div>
				<div class="button-container">
					<input type="submit" class="button button1" value="Sign Up" class="submit" />
				</div>
			</form>
		</div>
	</div>
</section>

templates/web/reservation_entry.html
	{% extends 'web/base.html' %}
	{% block content %}
		<form class="ajax reset {% if redirect %}redirect{% endif %} form form-container" method="post" action="{{url}}">
			{% csrf_token %}
			<h1>BOOK NOW</h1>
			<div>
				<label for="{{ form.client_name.id_for_label }}" class="">
				{{ form.client_name.label }}
				{% if form.client_name.field.required %}
				    <small class="star">*</small>
				{% endif %}
				{% if form.client_name.help_text %}
				    <span data-original-title="Field Info" title="" data-content="{{ form.client_name.help_text }}" aria-describedby="popover59326" data-placement="auto left" data-toggle="popover" data-trigger="hover" class="help-text-icon fa fa-info-circle" style="font-size:16px;">
				{% endif %}
				</label>
				{{ form.client_name }}

				{% if form.client_name.errors %}
				<label class="error">{{ form.client_name.errors.as_text }}</label>
				{% endif %}
			</div>
			<div>
				<label for="{{ form.client_address.id_for_label }}" class="">
				{{ form.client_address.label }}
				{% if form.client_address.field.required %}
				    <small class="star">*</small>
				{% endif %}
				{% if form.client_address.help_text %}
				    <span data-original-title="Field Info" title="" data-content="{{ form.client_address.help_text }}" aria-describedby="popover59326" data-placement="auto left" data-toggle="popover" data-trigger="hover" class="help-text-icon fa fa-info-circle" style="font-size:16px;">
				{% endif %}
				</label>
				{{ form.client_address }}

				{% if form.client_address.errors %}
				<label class="error">{{ form.client_address.errors.as_text }}</label>
				{% endif %}
			</div>
			<div>
				<label for="{{ form.from_date.id_for_label }}" class="">
				{{ form.from_date.label }}
				{% if form.from_date.field.required %}
				    <small class="star">*</small>
				{% endif %}
				{% if form.from_date.help_text %}
				    <span data-original-title="Field Info" title="" data-content="{{ form.from_date.help_text }}" aria-describedby="popover59326" data-placement="auto left" data-toggle="popover" data-trigger="hover" class="help-text-icon fa fa-info-circle" style="font-size:16px;">
				{% endif %}
				</label>
				{{ form.from_date }}

				{% if form.from_date.errors %}
				<label class="error">{{ form.from_date.errors.as_text }}</label>
				{% endif %}
			</div>
			<div>
				<label for="{{ form.to_date.id_for_label }}" class="">
				{{ form.to_date.label }}
				{% if form.to_date.field.required %}
				    <small class="star">*</small>
				{% endif %}
				{% if form.to_date.help_text %}
				    <span data-original-title="Field Info" title="" data-content="{{ form.to_date.help_text }}" aria-describedby="popover59326" data-placement="auto left" data-toggle="popover" data-trigger="hover" class="help-text-icon fa fa-info-circle" style="font-size:16px;">
				{% endif %}
				</label>
				{{ form.to_date }}

				{% if form.to_date.errors %}
				<label class="error">{{ form.to_date.errors.as_text }}</label>
				{% endif %}
			</div>
			
			<div>
				<label for="{{ form.city.id_for_label }}" class="">
				{{ form.city.label }}
				{% if form.city.field.required %}
				    <small class="star">*</small>
				{% endif %}
				{% if form.city.help_text %}
				    <span data-original-title="Field Info" title="" data-content="{{ form.city.help_text }}" aria-describedby="popover59326" data-placement="auto left" data-toggle="popover" data-trigger="hover" class="help-text-icon fa fa-info-circle" style="font-size:16px;">
				{% endif %}
				</label>
				{{ form.city }}

				{% if form.city.errors %}
				<label class="error">{{ form.city.errors.as_text }}</label>
				{% endif %}
			</div>
			<div>
				<label for="{{ form.zipcode.id_for_label }}" class="">
				{{ form.zipcode.label }}
				{% if form.zipcode.field.required %}
				    <small class="star">*</small>
				{% endif %}
				{% if form.zipcode.help_text %}
				    <span data-original-title="Field Info" title="" data-content="{{ form.zipcode.help_text }}" aria-describedby="popover59326" data-placement="auto left" data-toggle="popover" data-trigger="hover" class="help-text-icon fa fa-info-circle" style="font-size:16px;">
				{% endif %}
				</label>
				{{ form.zipcode }}

				{% if form.zipcode.errors %}
				<label class="error">{{ form.zipcode.errors.as_text }}</label>
				{% endif %}
			</div>
			<div>
				<label for="{{ form.email.id_for_label }}" class="">
				{{ form.email.label }}
				{% if form.email.field.required %}
				    <small class="star">*</small>
				{% endif %}
				{% if form.email.help_text %}
				    <span data-original-title="Field Info" title="" data-content="{{ form.email.help_text }}" aria-describedby="popover59326" data-placement="auto left" data-toggle="popover" data-trigger="hover" class="help-text-icon fa fa-info-circle" style="font-size:16px;">
				{% endif %}
				</label>
				{{ form.email }}

				{% if form.email.errors %}
				<label class="error">{{ form.email.errors.as_text }}</label>
				{% endif %}
			</div>
			<div>
				<label for="{{ form.phone.id_for_label }}" class="">
				{{ form.phone.label }}
				{% if form.phone.field.required %}
				    <small class="star">*</small>
				{% endif %}
				{% if form.phone.help_text %}
				    <span data-original-title="Field Info" title="" data-content="{{ form.phone.help_text }}" aria-describedby="popover59326" data-placement="auto left" data-toggle="popover" data-trigger="hover" class="help-text-icon fa fa-info-circle" style="font-size:16px;">
				{% endif %}
				</label>
				{{ form.phone }}

				{% if form.phone.errors %}
				<label class="error">{{ form.phone.errors.as_text }}</label>
				{% endif %}
			</div>
			
			<button type="submit" class="btn">BOOK NOW</button>
		</form>

	{% endblock %}
	{% block static %}		

	{% endblock %}

templates/web/reservations.html
{% extends 'web/base.html' %}
{% block content %}
<section class="reservations">
	<h4>My Bookings</h4>
	table
</section>
{% endblock %}
{% block static %}		
<script>
	$('[data-toggle="datepicker"]').datepicker({
		  startDate: "+0d",
		  format:'dd/mm/yyyy',
		  autoHide: 'True'
	});
</script>
{% endblock %}

templates/web/single.html
{% extends 'web/base.html' %}
{% load static %}
{% block content %}
	<section id="spotlight">
		<section class="wrapper">
			<h1>{{auditorium.name}}</h1>
			<p>{{auditorium.title}}</p>
			<div class="search">
			<form action="{% url 'web:check_availabilty' %}" class="ajax reset form" method="post">
				{% csrf_token %}
				<div class="date wid">
					<i class="icon icon-calendar"></i><input type="text" data-toggle="datepicker" name="sdate" placeholder="Date">
				</div>
				<div class="but wid">
					<input type="submit" class=" button" value="Check Availability" class="submit" />
				</div>
				<br class="clear" />
			</form>						
		</div>
		</section>
	</section>
	<section id="content">
		<section class="wrapper">
			<ul class="owl-carousel owl-theme">
				<li class="item">
					<img src="{% static 'web/images/g1.jpeg' %}" alt="">
				</li>
				<li class="item">
					<img src="{% static 'web/images/g1.jpeg' %}" alt="">
				</li>
				<li class="item">
					<img src="{% static 'web/images/g2.jpeg' %}" alt="">
				</li>
				<li class="item">
					<img src="{% static 'web/images/g3.jpeg' %}" alt="">
				</li>
				<li class="item">
					<img src="{% static 'web/images/g4.jpeg' %}" alt="">
				</li>
			</ul>
		</section>
		
	</section>
	<section class="basic">
		<section class="wrapper">
			<h1>Details</h1>
			<p>Address :- {{auditorium.address}}</p>
			<p>Location :- {{auditorium.location}}</p>
			<p>City :- {{auditorium.city}}</p>
			<p>District :- {{auditorium.district}}</p>
			<p>State :- {{auditorium.state}}</p>
			<p>Zipcode :- {{auditorium.zipcode}}</p>
			<p>Contact :- {{auditorium.contact1}}/{{auditorium.contact}}</p>
			<p>Email :- {{auditorium.email}}</p>
			<p>Rent :- {{auditorium.rent}}</p>
		</section>
	</section>
	{% if user_logined %}
		{% if current_role == 'customer' %}
			<a href="{% url 'web:book_now' pk=auditorium.pk %}" class="button">Book Now</a>
		{% endif %}
	{% else %}
	<a href="#" class="button user-login">Book Now</a>
	{% endif %}
{% endblock %}
{% block static %}		
<script>
	$(document).ready(function(){
	  	$(".owl-carousel").owlCarousel({
	  		loop:true,
			margin:10,
			autoplay:true,
			dots:false
	  	});
	});
</script>
{% endblock %}		
				