auditoriums/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views
from views import AuditoriumAutocomplete


urlpatterns = [               
	url(r'^partner-autocomplete/$',AuditoriumAutocomplete.as_view(),name='auditorium_autocomplete'), 
    url(r'^auditoriums/create/$',views.create_auditorium,name='create_auditorium'),
    url(r'^auditoriums/view/$',views.auditoriums,name='auditoriums'),
    url(r'^auditoriums/edit/(?P<pk>.*)/$',views.edit_auditorium,name='edit_auditorium'),
    url(r'^auditoriums/view/(?P<pk>.*)/$',views.auditorium,name='auditorium'),
    url(r'^auditoriums/delete/(?P<pk>.*)/$',views.delete_auditorium,name='delete_auditorium'),
    url(r'^auditoriums/delete-selected-auditoriums/$', views.delete_selected_auditoriums, name='delete_selected_auditoriums'), 
]

audta/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.static import serve
from main import views as general_views
from django.conf import settings
from registration.backends.default.views import RegistrationView
from users.forms import RegForm
from users.backend import user_created
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin', admin.site.urls),

    url(r'^', include('web.urls', namespace="web")),
    url(r'^app/$',general_views.app,name='app'),
    url(r'^report/$',general_views.report,name='report'),
    url(r'^app/dashboard/$',general_views.dashboard,name='dashboard'),
    url(r'^app/auditorium/', include('auditoriums.urls', namespace="auditoriums")),
    url(r'^app/partner/', include('partners.urls', namespace="partners")),
    url(r'^app/resrvation/', include('reservations.urls', namespace="reservations")),

    url(r'^app/accounts/register/$', RegistrationView.as_view(form_class=RegForm),name='registration_register'),
    url(r'^app/accounts/', include('registration.backends.default.urls')), 

    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT}),
]

partners/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views
from views import PartnerAutocomplete


urlpatterns = [               
	url(r'^partner-autocomplete/$',PartnerAutocomplete.as_view(),name='partner_autocomplete'), 
    url(r'^partners/create/$',views.create_partner,name='create_partner'),
    url(r'^partners/view/$',views.partners,name='partners'),
    url(r'^partners/edit/(?P<pk>.*)/$',views.edit_partner,name='edit_partner'),
    url(r'^partners/view/(?P<pk>.*)/$',views.partner,name='partner'),
    url(r'^partners/delete/(?P<pk>.*)/$',views.delete_partner,name='delete_partner'),
    url(r'^partners/delete-selected-partners/$', views.delete_selected_partners, name='delete_selected_partners'),

    url(r'^partners/make-user/(?P<pk>.*)/$',views.make_user,name='make_user'),
]

reservations/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views


urlpatterns = [               
    url(r'^reservations/create/$',views.create_reservation,name='create_reservation'),
    url(r'^reservations/view/$',views.reservations,name='reservations'),
    url(r'^reservations/delete/(?P<pk>.*)/$',views.delete_reservation,name='delete_reservation'),
    url(r'^reservations/cancel/(?P<pk>.*)/$',views.cancel_reservation,name='cancel_reservation'),
    
]

web/urls.py
from django.conf.urls import url, include
import views

urlpatterns = [               

    url(r'^$', views.index,name='index'), 
   
    url(r'^single/(?P<pk>.*)/$', views.single,name='single'),
   	url(r'^customer-registration/$', views.customer_registration, name='customer_registration'), 
    url(r'^login/$', views.customer_login, name='customer_login'),
    url(r'^customer/logout/$', views.logout, name='logout'),

    url(r'^book-now/(?P<pk>.*)/$', views.book_now,name='book_now'),
    url(r'^booking-list/$', views.reservations, name='reservations'),
    url(r'^print-booking/(?P<pk>.*)/$', views.print_reservation,name='print_reservation'),
    url(r'^check-availabilty/$', views.check_availabilty, name='check_availabilty'), 
    
]

templates/includes/menu.html
<li>
    <a href="{% url 'dashboard' %}"><i class="fa fa-area-chart"></i> <span class="nav-label"><b>DashBoard</b> </span></a>
</li>


{% if user in super_users  or 'can_manage_customer_badge_offer' in user_instance.permissionlist %}
<li>
    <a href=""><i class="fa fa-tags"></i> <span class="nav-label">Auditoriums</span><span class="fa arrow"></span></a>
    <ul class="nav nav-second-level collapse">
        
        <li>
            <a href="{% url 'auditoriums:create_auditorium' %}">Create</a>
        </li>
        <li>
            <a href="{% url 'auditoriums:auditoriums' %}">List</a>
        </li>
    </ul>
</li>
<li>
    <a href=""><i class="fa fa-tags"></i> <span class="nav-label">Partners</span><span class="fa arrow"></span></a>
    <ul class="nav nav-second-level collapse">
        
        <li>
            <a href="{% url 'partners:create_partner' %}">Create</a>
        </li>
        <li>
            <a href="{% url 'partners:partners' %}">List</a>
        </li>
    </ul>
</li>
<li>
    <a href=""><i class="fa fa-tags"></i> <span class="nav-label">Bookings</span><span class="fa arrow"></span></a>
    <ul class="nav nav-second-level collapse">
        
        <li>
            <a href="{% url 'reservations:create_reservation' %}">Create</a>
        </li>
        <li>
            <a href="{% url 'reservations:reservations' %}">List</a>
        </li>
    </ul>
</li>
{% endif %}

templates/includes/messages.html
{% load static %}
<li class="dropdown">
    <a class="dropdown-toggle count-info" data-toggle="dropdown" href="">
        <i class="fa fa-envelope"></i>  <span class="label label-warning">16</span>
    </a>
    <ul class="dropdown-menu dropdown-messages">
        <li>
            <div class="dropdown-messages-box">
                <a href="" class="pull-left">
                    <img alt="image" class="img-circle" src="{% static 'img/a7.jpg' %}">
                </a>
                <div class="media-body">
                    <small class="pull-right">46h ago</small>
                    <strong>Mike Loreipsum</strong> started following <strong>Monica Smith</strong>. <br>
                    <small class="text-muted">3 days ago at 7:58 pm - 10.06.2014</small>
                </div>
            </div>
        </li>
        <li class="divider"></li>
        <li>
            <div class="dropdown-messages-box">
                <a href="" class="pull-left">
                    <img alt="image" class="img-circle" src="{% static 'img/a4.jpg' %}">
                </a>
                <div class="media-body ">
                    <small class="pull-right text-navy">5h ago</small>
                    <strong>Chris Johnatan Overtunk</strong> started following <strong>Monica Smith</strong>. <br>
                    <small class="text-muted">Yesterday 1:21 pm - 11.06.2014</small>
                </div>
            </div>
        </li>
        <li class="divider"></li>
        <li>
            <div class="dropdown-messages-box">
                <a href="" class="pull-left">
                    <img alt="image" class="img-circle" src="{% static 'img/profile.jpg' %}">
                </a>
                <div class="media-body ">
                    <small class="pull-right">23h ago</small>
                    <strong>Monica Smith</strong> love <strong>Kim Smith</strong>. <br>
                    <small class="text-muted">2 days ago at 2:30 am - 11.06.2014</small>
                </div>
            </div>
        </li>
        <li class="divider"></li>
        <li>
            <div class="text-center link-block">
                <a href="">
                    <i class="fa fa-envelope"></i> <strong>Read All Messages</strong>
                </a>
            </div>
        </li>
    </ul>
</li>

templates/includes/not_found.html
<div class="ibox p-md">
	<div class="m-b-none p-md">Nothing found.</div>
</div>

templates/includes/notifications.html
{% load humanize %}
{% load tz %}

<li class="dropdown">
    <a class="dropdown-toggle count-info" data-toggle="dropdown" href="">
        <i class="fa fa-bell"></i>  <span class="label label-primary">{{notification_count}}</span>
    </a>
    <ul class="dropdown-menu dropdown-alerts">
        <li>
            <a href="">
                <div>
                    <i class="fa fa-envelope fa-fw"></i> You have {{notification_count}} notifications
                </div>
            </a>
        </li>
        <li class="divider"></li>
        {% for notification in recent_notifications %}
            <li>

                {% if notification.subject.code == "cash_on_delivary_order" %}
                    <a href="{% url 'sales:order' pk=notification.order.pk %}">
                        <div>
                            <i class="fa fa-tasks fa-fw"></i> New Cash on delivery order ({{notification.order.order_id}}) placed.
                            <span class="pull-right text-muted small">{{notification.time|timezone:user_time_zone|naturaltime}}</span>
                        </div>
                    </a>
                {% elif notification.subject.code == "order_status_updated" %}
                    <a href="{% url 'sales:order' pk=notification.order.pk %}">
                        <div>
                            <i class="fa fa-tasks fa-fw"></i> Order({{notification.order.order_id}}) status updated to {{notification.order_status}}                  
                            <span class="pull-right text-muted small">{{notification.time|timezone:user_time_zone|naturaltime}}</span>
                        </div>
                    </a>
                {% elif notification.subject.code == "product_unverified" %}
                    <a href="{% url 'products:product' pk=notification.product.pk %}">
                        <div>
                            <i class="fa fa-chain-broken fa-fw"></i> Product {{notification.product.name}} Unverified.                   
                            <span class="pull-right text-muted small">{{notification.time|timezone:user_time_zone|naturaltime}}</span>
                        </div>
                    </a>
                {% elif notification.subject.code == "product_verified" %}
                    <a href="{% url 'products:product' pk=notification.product.pk %}">
                        <div>
                            <i class="fa fa-check fa-fw"></i> Product {{notification.product.name}} Verified.                    
                            <span class="pull-right text-muted small">{{notification.time|timezone:user_time_zone|naturaltime}}</span>
                        </div>
                    </a>
                {% endif %}
            </li>
            <li class="divider"></li>
        {% endfor %}
        <li>
            <div class="text-center link-block">
                <a href="">
                    <strong>See All Alerts</strong>
                    <i class="fa fa-angle-right"></i>
                </a>
            </div>
        </li>
    </ul>
</li>

templates/includes/shortcuts.html
<div class="shortcuts">
	<button class="btn palette-Light-Blue btn-icon bg waves-effect waves-circle waves-float">
		<i class="zmdi zmdi-plus"></i>
	</button>
	
	<div class="icons icons text-right">
		<a href="" class="btn palette-Blue bg btn-icon-text waves-effect">Purchase<i class="zmdi zmdi-shopping-cart"></i></a>
		<br />
		<a href="" class="btn palette-Indigo bg btn-icon-text waves-effect">Vendor <i class="zmdi m-l-10 zmdi-view-list"></i></a>
		<br />
		<a href="{% url 'customers:customers' %}" class="btn btn-warning bg btn-icon-text waves-effect">Customer <i class="palette-Purple bg zmdi zmdi-accounts-alt"></i></a>
		<br />
		<a href="{% url 'products:products' %}" class="btn palette-Teal bg btn-icon-text waves-effect">Product <i class="zmdi m-l-10 zmdi-view-comfy"></i></a>
		<br />
		<a href="" class="btn btn-info bg btn-icon-text waves-effect">Sale <i class="zmdi zmdi-city-alt"></i></a>
		<br />
		<a href="" class="btn palette-Red bg btn-icon-text waves-effect">Task <i class="zmdi m-l-10 zmdi-view-list"></i></a>
		<br />
		<a href="" class="btn palette-Pink bg btn-icon-text waves-effect">Staffs <i class="palette-Cyan bg zmdi zmdi-account"></i></a>
		<br />
		<a href="" class="btn palette-Green bg btn-icon-text waves-effect">Finance <i class="zmdi m-l-10 zmdi-money"></i></a>
		<br />
	</div>
</div>