auditoriums/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views
from views import AuditoriumAutocomplete


urlpatterns = [               
	url(r'^partner-autocomplete/$',AuditoriumAutocomplete.as_view(),name='auditorium_autocomplete'), 
    url(r'^auditoriums/create/$',views.create_auditorium,name='create_auditorium'),
    url(r'^auditoriums/view/$',views.auditoriums,name='auditoriums'),
    url(r'^auditoriums/edit/(?P<pk>.*)/$',views.edit_auditorium,name='edit_auditorium'),
    url(r'^auditoriums/view/(?P<pk>.*)/$',views.auditorium,name='auditorium'),
    url(r'^auditoriums/delete/(?P<pk>.*)/$',views.delete_auditorium,name='delete_auditorium'),
    url(r'^auditoriums/delete-selected-auditoriums/$', views.delete_selected_auditoriums, name='delete_selected_auditoriums'), 
]

audta/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.static import serve
from main import views as general_views
from django.conf import settings
from registration.backends.default.views import RegistrationView
from users.forms import RegForm
from users.backend import user_created
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin', admin.site.urls),

    url(r'^', include('web.urls', namespace="web")),
    url(r'^app/$',general_views.app,name='app'),
    url(r'^report/$',general_views.report,name='report'),
    url(r'^app/dashboard/$',general_views.dashboard,name='dashboard'),
    url(r'^app/auditorium/', include('auditoriums.urls', namespace="auditoriums")),
    url(r'^app/partner/', include('partners.urls', namespace="partners")),
    url(r'^app/resrvation/', include('reservations.urls', namespace="reservations")),

    url(r'^app/accounts/register/$', RegistrationView.as_view(form_class=RegForm),name='registration_register'),
    url(r'^app/accounts/', include('registration.backends.default.urls')), 

    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT}),
]

reservations/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views


urlpatterns = [               
    url(r'^reservations/create/$',views.create_reservation,name='create_reservation'),
    url(r'^reservations/view/$',views.reservations,name='reservations'),
    url(r'^reservations/delete/(?P<pk>.*)/$',views.delete_reservation,name='delete_reservation'),
    url(r'^reservations/cancel/(?P<pk>.*)/$',views.cancel_reservation,name='cancel_reservation'),
    
]

web/urls.py
from django.conf.urls import url, include
import views

urlpatterns = [               

    url(r'^$', views.index,name='index'), 
   
    url(r'^single/(?P<pk>.*)/$', views.single,name='single'),
   	url(r'^customer-registration/$', views.customer_registration, name='customer_registration'), 
    url(r'^login/$', views.customer_login, name='customer_login'),
    url(r'^customer/logout/$', views.logout, name='logout'),

    url(r'^book-now/(?P<pk>.*)/$', views.book_now,name='book_now'),
    url(r'^booking-list/$', views.reservations, name='reservations'),
    url(r'^print-booking/(?P<pk>.*)/$', views.print_reservation,name='print_reservation'),
    url(r'^check-availabilty/$', views.check_availabilty, name='check_availabilty'), 
    
]

reservations/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.core.validators import MinValueValidator
from django.utils.translation import ugettext_lazy as _
from decimal import Decimal
from versatileimagefield.fields import VersatileImageField
from main.models import BaseModel

STATUS = (
    ('booked', 'Booked'),
    ('cancelled', 'Cancelled'),
    ('completed', 'Completed'),
)


class Reservation(BaseModel):
    auditorium = models.ForeignKey("auditoriums.Auditorium")
    customer = models.ForeignKey("customers.Customer",null=True,blank=True)
    from_date = models.DateTimeField()
    to_date = models.DateTimeField(null=True,blank=True) 
    client_name = models.CharField(max_length=256)
    client_address = models.CharField(max_length=128)
    city = models.CharField(max_length=128)
    zipcode = models.CharField(max_length=128)
    phone = models.CharField(max_length=128)
    email = models.EmailField(null=True,blank=True)
    amount = models.DecimalField(default=0.00,blank=True,decimal_places=2, max_digits=15, validators=[MinValueValidator(Decimal('0.00'))])
    is_deleted = models.BooleanField(default=False)
    status = models.CharField(max_length=128,choices=STATUS)

    class Meta:
        db_table = 'reservations'
        verbose_name = _('reservation')
        verbose_name_plural = _('reservations')
        ordering = ('id',)
        
    class Admin:
        list_display = ('id',)

    def __unicode__(self):
        return self.title

reservations/forms.py
from django.utils.translation import ugettext_lazy as _
from django import forms
from django.forms.widgets import TextInput,Textarea,Select,DateInput, CheckboxInput
from django.contrib.auth.models import User
from reservations.models import Reservation
from dal import autocomplete


class ReservationForm(forms.ModelForm):

	class Meta:
		model = Reservation
		exclude = ['creator','updator','auto_id','is_deleted','amount','customer','status']
		widgets = {
			'auditorium': autocomplete.ModelSelect2(url='auditoriums:auditorium_autocomplete', attrs={'data-placeholder': 'Auditorium', 'data-minimum-input-length': 1},), 
			'from_date': TextInput(attrs={'class': 'required form-control date-picker','placeholder' : 'From Date'}),
			'to_date': TextInput(attrs={'class': 'form-control date-picker','placeholder' : 'To Date'}),
			'client_name': TextInput(attrs={'class': 'required form-control','placeholder' : 'Name'}),
			'client_address': TextInput(attrs={'class': 'required form-control','placeholder' : 'Address'}),
			'city': TextInput(attrs={'class': 'required form-control','placeholder' : 'City'}),
			'zipcode': TextInput(attrs={'class': 'required form-control','placeholder' : 'ZIP'}),
			'phone': TextInput(attrs={'class': 'required form-control number','placeholder' : 'Phone'}),
			'email': TextInput(attrs={'class': 'required form-control','placeholder' : 'Email'}),
			
		}

		error_messages = {
			'name' : {
				'required' : _("Product field is required."),
			},
			'Address' : {
				'required' : _("Offer percentage field is required."),
			},
			'district' : {
				'required' : _("Start date field is required."),
			},
			'state' : {
				'required' : _("End Date field is required."),
			},
			'contact1' : {
				'required' : _("End Date field is required."),
			},
			'contact2' : {
				'required' : _("End Date field is required."),
			},
			'zipcode' : {
				'required' : _("End Date field is required."),
			},
		}

reservations/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render,get_object_or_404
from django.http.response import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from reservations.models import Reservation
from reservations.forms import ReservationForm
from django.contrib.auth.decorators import login_required
from main.decorators import check_mode,role_required
from main.functions import get_auto_id,generate_form_errors
import json
import datetime


# Create your views here.
@check_mode
@login_required
@role_required(['partner','superadmin','administrator'])
def create_reservation(request):

    if request.method == 'POST':
        form = ReservationForm(request.POST,request.FILES)
        
        if form.is_valid():


            data = form.save(commit=False)
            data.creator = request.user
            data.updator = request.user
            data.auto_id = get_auto_id(Reservation)
            data.status = 'booked'
            data.save() 

            response_data = {
                "status" : "true",
                "title" : "Successfully Created",
                "message" : "Reservation(s) created successfully.",
                "redirect" : "true",
                "redirect_url" : reverse('reservations:reservations')
            }

        else:
            message = generate_form_errors(form, formset=False)
            response_data = {
                "status" : "false",
                "stable" : "true",
                "title" : "Form validation error",
                "message" : message
            }   
        return HttpResponse(json.dumps(response_data), content_type='application/javascript')
    else:
        form = ReservationForm()

        context = {
            "title": "Create Reservation",
            "url": reverse('reservations:create_reservation'),
            "form" : form,
            "redirect" : True,

            "is_need_popup_box": True,
            "is_need_grid_system": True,
            "is_need_animations": True,
            "is_need_datetime_picker": True,
            "is_need_checkbox": True,
            "is_need_select_picker" : True,
            "is_need_formset" : True,
        }
        return render(request,'reservations/entry.html',context)


@check_mode
@login_required
@role_required(['partner','superadmin','administrator'])
def reservations(request):
    instances = Reservation.objects.filter(is_deleted=False)
    title = "reservations"

    query = request.GET.get("q")
    if query:
        instances = instances.filter(Q(name__icontains=query))
        title = "reservations - %s" % query

    context = {
        "instances": instances,
        'title': title,

        "is_need_popup_box": True,
        "is_need_grid_system": True,
        "is_need_animations": True,
        "is_need_datetime_picker": True,
        "is_need_checkbox": True
    }
    return render(request, 'reservations/reservations.html', context)


@check_mode
@login_required
@role_required(['partner','superadmin','administrator'])
def delete_reservation(request,pk):
    instance = get_object_or_404(Reservation.objects.filter(pk=pk,is_deleted=False))
    
    Reservation.objects.filter(pk=pk).update(is_deleted=True)
    
    response_data = {
        "status" : "true",
        "title" : "Successfully Deleted",
        "message" : "Reservation Successfully Deleted.",
        "redirect" : "true",
        "redirect_url" : reverse('reservations:reservations')
    }
    return HttpResponse(json.dumps(response_data), content_type='application/javascript')


@check_mode
@login_required
@role_required(['partner','superadmin','administrator'])
def cancel_reservation(request,pk):
    instance = get_object_or_404(Reservation.objects.filter(pk=pk,is_deleted=False))
    
    Reservation.objects.filter(pk=pk).update(status="cancelled")
    
    response_data = {
        "status" : "true",
        "title" : "Successfully Cancelled",
        "message" : "Reservation Successfully Cancelled.",
        "redirect" : "true",
        "redirect_url" : reverse('reservations:reservations')
    }
    return HttpResponse(json.dumps(response_data), content_type='application/javascript')

templates/reservations/entry.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block content %}
    <div class="row wrapper border-bottom white-bg p-h-xs">
        <div class="col-lg-12">
            <div class="row">
            <div class="col-lg-7">
                <h3>{{title}}</h3>
            </div>
            <div class="col-lg-5">
                <ul class="list-unstyled list-inline text-right m-r-md m-b-none m-t-sm">
                    <li class="no-margins">
                        <a  style="font-size:15px;" class="p-xxs" title="List"  href="{% url 'auditoriums:auditoriums' %}">
                            <i class="fa fa-list text-navy"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        <form class="ajax reset {% if redirect %}redirect{% endif %} form" method="post" action="{{url}}">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-6">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h4>Basic Details</h4>
                        </div>
                        <div class="ibox-content p-md">
                            <div class="form-group">
                                <label for="{{ form.auditorium.id_for_label }}" class="">
                                    {{ form.auditorium.label }}
                                    {% if form.auditorium.field.required %}
                                        <small class="star">*</small>
                                    {% endif %}
                                    {% if form.auditorium.help_text %}
                                        <span data-original-title="Field Info" title="" data-content="{{ form.auditorium.help_text }}" aria-describedby="popover59326" data-placement="auto left" data-toggle="popover" data-trigger="hover" class="help-text-icon fa fa-info-circle" style="font-size:16px;">
                                    {% endif %}
                                </label>
                                {{ form.auditorium }}
                                
                                {% if form.auditorium.errors %}
                                    <label class="error">{{ form.auditorium.errors.as_text }}</label>
                                {% endif %}
                            </div>
                            <div class="form-group">
                                <label for="{{ form.client_name.id_for_label }}" class="">
                                    {{ form.client_name.label }}
                                    {% if form.client_name.field.required %}
                                        <small class="star">*</small>
                                    {% endif %}
                                    {% if form.client_name.help_text %}
                                        <span data-original-title="Field Info" title="" data-content="{{ form.client_name.help_text }}" aria-describedby="popover59326" data-placement="auto left" data-toggle="popover" data-trigger="hover" class="help-text-icon fa fa-info-circle" style="font-size:16px;">
                                    {% endif %}
                                </label>
                                {{ form.client_name }}
                                
                                {% if form.client_name.errors %}
                                    <label class="error">{{ form.client_name.errors.as_text }}</label>
                                {% endif %}
                            </div>

                            <div class="form-group">
                                <label for="{{ form.client_address.id_for_label }}">
                                    {{ form.client_address.label }}
                                    {% if form.client_address.field.required %}
                                        <small class="star">*</small>
                                    {% endif %}
                                    {% if form.client_address.help_text %}
                                        <span data-original-client_address="Field Info" client_address="" data-content="{{ form.client_address.help_text }}" aria-describedby="popover59326" data-placement="auto left" data-toggle="popover" data-trigger="hover" class="help-text-icon fa fa-info-circle" style="font-size:16px;">
                                    {% endif %}
                                </label>
                                {{ form.client_address }}
                                
                                {% if form.client_address.errors %}
                                    <label class="error">{{ form.client_address.errors.as_text }}</label>
                                {% endif %}
                            </div>

                            <div class="form-group">
                                <label for="{{ form.from_date.id_for_label }}">
                                    {{ form.from_date.label }}
                                    {% if form.from_date.field.required %}
                                        <small class="star">*</small>
                                    {% endif %}
                                    {% if form.from_date.help_text %}
                                        <span data-original-title="Field Info" title="" data-content="{{ form.from_date.help_text }}" aria-describedby="popover59326" data-placement="auto left" data-toggle="popover" data-trigger="hover" class="help-text-icon fa fa-info-circle" style="font-size:16px;">
                                    {% endif %}
                                </label>
                                {{ form.from_date }}
                                
                                {% if form.from_date.errors %}
                                    <label class="error">{{ form.from_date.errors.as_text }}</label>
                                {% endif %}
                            </div>

                            <div class="form-group">
                                <label for="{{ form.to_date.id_for_label }}" class="">
                                    {{ form.to_date.label }}
                                    {% if form.to_date.field.required %}
                                        <small class="star">*</small>
                                    {% endif %}
                                    {% if form.to_date.help_text %}
                                        <span data-original-title="Field Info" title="" data-content="{{ form.to_date.help_text }}" aria-describedby="popover59326" data-placement="auto left" data-toggle="popover" data-trigger="hover" class="help-text-icon fa fa-info-circle" style="font-size:16px;">
                                    {% endif %}
                                </label>
                                {{ form.to_date }}
                                
                                {% if form.to_date.errors %}
                                    <label class="error">{{ form.to_date.errors.as_text }}</label>
                                {% endif %}
                            </div>

                            <div class="form-group">
                                <label for="{{ form.city.id_for_label }}">
                                    {{ form.city.label }}
                                    {% if form.city.field.required %}
                                        <small class="star">*</small>
                                    {% endif %}
                                    {% if form.city.help_text %}
                                        <span data-original-title="Field Info" title="" data-content="{{ form.city.help_text }}" aria-describedby="popover59326" data-placement="auto left" data-toggle="popover" data-trigger="hover" class="help-text-icon fa fa-info-circle" style="font-size:16px;">
                                    {% endif %}
                                </label>
                                {{ form.city }}
                                
                                {% if form.city.errors %}
                                    <label class="error">{{ form.city.errors.as_text }}</label>
                                {% endif %}
                            </div>

                            <div class="form-group">
                                <label for="{{ form.zipcode.id_for_label }}">
                                    {{ form.zipcode.label }}
                                    {% if form.zipcode.field.required %}
                                        <small class="star">*</small>
                                    {% endif %}
                                    {% if form.zipcode.help_text %}
                                        <span data-original-title="Field Info" title="" data-content="{{ form.zipcode.help_text }}" aria-describedby="popover59326" data-placement="auto left" data-toggle="popover" data-trigger="hover" class="help-text-icon fa fa-info-circle" style="font-size:16px;">
                                    {% endif %}
                                </label>
                                {{ form.zipcode }}
                                
                                {% if form.zipcode.errors %}
                                    <label class="error">{{ form.zipcode.errors.as_text }}</label>
                                {% endif %}
                            </div>

                            <div class="form-group">
                                <label for="{{ form.email.id_for_label }}">
                                    {{ form.email.label }}
                                    {% if form.email.field.required %}
                                        <small class="star">*</small>
                                    {% endif %}
                                    {% if form.email.help_text %}
                                        <span data-original-title="Field Info" title="" data-content="{{ form.email.help_text }}" aria-describedby="popover59326" data-placement="auto left" data-toggle="popover" data-trigger="hover" class="help-text-icon fa fa-info-circle" style="font-size:16px;">
                                    {% endif %}
                                </label>
                                {{ form.email }}
                                
                                {% if form.email.errors %}
                                    <label class="error">{{ form.email.errors.as_text }}</label>
                                {% endif %}
                            </div>

                            <div class="form-group">
                                <label for="{{ form.phone.id_for_label }}">
                                    {{ form.phone.label }}
                                    {% if form.phone.field.required %}
                                        <small class="star">*</small>
                                    {% endif %}
                                    {% if form.phone.help_text %}
                                        <span data-original-title="Field Info" title="" data-content="{{ form.phone.help_text }}" aria-describedby="popover59326" data-placement="auto left" data-toggle="popover" data-trigger="hover" class="help-text-icon fa fa-info-circle" style="font-size:16px;">
                                    {% endif %}
                                </label>
                                {{ form.phone }}
                                
                                {% if form.phone.errors %}
                                    <label class="error">{{ form.phone.errors.as_text }}</label>
                                {% endif %}
                            </div>
                        </div>
                    </div>

                </div>
               
            </div>

            <div class="m-b-md">
                <button class="btn btn-sm btn-primary" type="submit"><strong>Submit</strong></button>
            </div>
        </form>
    </div>

{% endblock %}
{% block static %}
{{form.media}}
{% endblock %}

templates/reservations/reservations.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load main_template_tags %}
{% load tz %}
{% block content %}
    <div>
        <div class="row wrapper border-bottom white-bg p-h-xs">
            <div class="col-lg-12">
                <div class="row">
                    <div class="col-lg-5">
                        <h3>{{title}}</h3>
                    </div>
                    
                    <div class="col-lg-7">
                        <div class="row">
                            <div class="col-lg-7">
                                <form action="" class="form-inline">
                                    <div class="input-group">
                                        <input type="text" placeholder="Search" class="input-sm form-control" name="q"> 
                                        <span class="input-group-btn">
                                            <button type="submit" class="btn btn-sm btn-primary"> Go!</button>
                                        </span>
                                    </div>
                                </form>
                            </div>
                        </div>   
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
            {% if instances %}
                <div class="ibox float-e-margins">
                    <div class="ibox-content">
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Name</th>
                                        <th>Address</th>
                                        <th>Duration</th>
                                        <th>Pincode</th>
                                        <th>Email</th>
                                        <th>Contact</th>
                                        <th>Status</th>
                                        <th class="text-right three">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% load el_pagination_tags %}
                                {% paginate 8 instances %}
                                {% for instance in instances %}
                                    <tr>
                                        <td>{{instance.auto_id}}</td>
                                        <td>{{instance.client_name}}</td>
                                        <td>{{instance.client_address}}</td>
                                        <td>{{instance.from_date|date:"d/m/Y"}} - {{instance.to_date|date:"d/m/Y"}}</td>
                                        <td>{{instance.zipcode}}</td>
                                        <td>{{instance.email}}</td>
                                        <td>{{instance.phone}}</td>
                                        
                                        <td style="{% if instance.status == 'booked' %}color:green{% elif instance.status == 'cancelled' %}color:red{% endif %}">{{instance.get_status_display}}</td>
                                        
                                        <td class="text-right">
                                            <a data-id="{{instance.pk}}" href="{% url 'reservations:delete_reservation' pk=instance.pk %}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" class="action-button remove run-function-after btn btn-white" data-function="change_after_delete"><i class="fa fa-trash text-navy"></i></a>
                                            {% if instance.status == 'booked' %}
                                            <a data-id="{{instance.pk}}" href="{% url 'reservations:cancel_reservation' pk=instance.pk %}" data-text="{{confirm_cancel_message}}" data-title="Are you sure?" class="action-button run-function-after btn btn-white" data-function="change_after_delete"><i class="fa fa-close text-navy"></i></a>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div> 
                <!--pagination -->
                <div class="bootgrid-footer container-fluid" id="data-table-selection-footer">
                    {% get_pages %}
                    <div class="row">
                        <div class="col-sm-6 text-left">
                            <div class="pagination">
                                {% show_pages %}
                            </div>
                        </div>
                        <div class="col-sm-6 infoBar text-right m-t-md">
                            <div class="infos">
                                Showing {{title}} <span class="current_page_index">{{ pages.current_start_index }}</span> - <span class="current_end_status">{{ pages.current_end_index }}</span> of <span class="total_count">{{ pages.total_count }}</span>
                            </div>
                        </div>
                    </div>
                </div>   
                <!--pagination-->
                {% else %}
                    {% include 'includes/not_found.html' %}
                {% endif %}   
            </div><!-- div.col-lg-12 -->

        </div><!-- div.row -->
    </div> <!-- div.wrapper -->
{% endblock %}

{% block filter_box %}
<div class="filter-box">
     <form method="get" action="">
        <div class="ibox">
            <div class="ibox-header p-xs">
                <h4 style="display: inline-block;">Filter <small></small></h4>
                <span class="back-button-poupup palette-Cyan bg white btn btn-default btn-icon-text waves-effect"><i class="fa fa-arrow-circle-o-left"></i> Back</span>
            </div>
            
            <div class="ibox-content">
                <div class="form-group">
                    <label>Query</label>
                    <input name="q" type="text" class="form-control" placeholder="Enter your query..." />
                </div>
                
                 <div class="m-t-20">
                    <button type="submit" class="btn btn-info waves-effect">Submit</button>
                </div>
            </div>
         </div>
     </form>
</div>
{% endblock %}


{% block static %}
    {% load static %}
{% endblock %}