auditoriums/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views
from views import AuditoriumAutocomplete


urlpatterns = [               
	url(r'^partner-autocomplete/$',AuditoriumAutocomplete.as_view(),name='auditorium_autocomplete'), 
    url(r'^auditoriums/create/$',views.create_auditorium,name='create_auditorium'),
    url(r'^auditoriums/view/$',views.auditoriums,name='auditoriums'),
    url(r'^auditoriums/edit/(?P<pk>.*)/$',views.edit_auditorium,name='edit_auditorium'),
    url(r'^auditoriums/view/(?P<pk>.*)/$',views.auditorium,name='auditorium'),
    url(r'^auditoriums/delete/(?P<pk>.*)/$',views.delete_auditorium,name='delete_auditorium'),
    url(r'^auditoriums/delete-selected-auditoriums/$', views.delete_selected_auditoriums, name='delete_selected_auditoriums'), 
]

audta/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.static import serve
from main import views as general_views
from django.conf import settings
from registration.backends.default.views import RegistrationView
from users.forms import RegForm
from users.backend import user_created
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin', admin.site.urls),

    url(r'^', include('web.urls', namespace="web")),
    url(r'^app/$',general_views.app,name='app'),
    url(r'^report/$',general_views.report,name='report'),
    url(r'^app/dashboard/$',general_views.dashboard,name='dashboard'),
    url(r'^app/auditorium/', include('auditoriums.urls', namespace="auditoriums")),
    url(r'^app/partner/', include('partners.urls', namespace="partners")),
    url(r'^app/resrvation/', include('reservations.urls', namespace="reservations")),

    url(r'^app/accounts/register/$', RegistrationView.as_view(form_class=RegForm),name='registration_register'),
    url(r'^app/accounts/', include('registration.backends.default.urls')), 

    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT}),
]

partners/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views
from views import PartnerAutocomplete


urlpatterns = [               
	url(r'^partner-autocomplete/$',PartnerAutocomplete.as_view(),name='partner_autocomplete'), 
    url(r'^partners/create/$',views.create_partner,name='create_partner'),
    url(r'^partners/view/$',views.partners,name='partners'),
    url(r'^partners/edit/(?P<pk>.*)/$',views.edit_partner,name='edit_partner'),
    url(r'^partners/view/(?P<pk>.*)/$',views.partner,name='partner'),
    url(r'^partners/delete/(?P<pk>.*)/$',views.delete_partner,name='delete_partner'),
    url(r'^partners/delete-selected-partners/$', views.delete_selected_partners, name='delete_selected_partners'),

    url(r'^partners/make-user/(?P<pk>.*)/$',views.make_user,name='make_user'),
]

web/urls.py
from django.conf.urls import url, include
import views

urlpatterns = [               

    url(r'^$', views.index,name='index'), 
   
    url(r'^single/(?P<pk>.*)/$', views.single,name='single'),
   	url(r'^customer-registration/$', views.customer_registration, name='customer_registration'), 
    url(r'^login/$', views.customer_login, name='customer_login'),
    url(r'^customer/logout/$', views.logout, name='logout'),

    url(r'^book-now/(?P<pk>.*)/$', views.book_now,name='book_now'),
    url(r'^booking-list/$', views.reservations, name='reservations'),
    url(r'^print-booking/(?P<pk>.*)/$', views.print_reservation,name='print_reservation'),
    url(r'^check-availabilty/$', views.check_availabilty, name='check_availabilty'), 
    
]

partners/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.validators import MinValueValidator
from django.utils.translation import ugettext_lazy as _
from decimal import Decimal
from versatileimagefield.fields import VersatileImageField
from main.models import BaseModel


class Partner(BaseModel):
    user = models.OneToOneField("auth.user",blank=True,null=True)
    name = models.CharField(max_length=128)
    address = models.CharField(max_length=256)
    district = models.CharField(max_length=128)
    state = models.CharField(max_length=128)
    zipcode = models.CharField(max_length=128)
    contact1 = models.CharField(max_length=128)
    contact2 = models.CharField(max_length=128)
    email = models.EmailField(null=True,blank=True)
    photo = VersatileImageField(upload_to="uploads/partners/",blank=True,null=True)
    is_deleted = models.BooleanField(default=False)

    class Meta:
        db_table = 'partners'
        verbose_name = _('partner')
        verbose_name_plural = _('partners')
        ordering = ('name',)
        
    class Admin:
        list_display = ('name',)

    def __unicode__(self):
        return self.name

partners/forms.py
from django.utils.translation import ugettext_lazy as _
from django import forms
from django.forms.widgets import TextInput,Textarea,Select,DateInput, CheckboxInput
from django.contrib.auth.models import User
from partners.models import Partner


class PartnerForm(forms.ModelForm):

    class Meta:
        model = Partner
        exclude = ['creator','updator','auto_id','is_deleted']
        widgets = {
           'name': TextInput(attrs={'class': 'required form-control','placeholder' : 'Name'}),
           'address': TextInput(attrs={'class': 'required form-control','placeholder' : 'Address'}),
           'district': TextInput(attrs={'class': 'required form-control','placeholder' : 'District'}),
           'state': TextInput(attrs={'class': 'required form-control','placeholder' : 'State'}),
           'zipcode': TextInput(attrs={'class': 'required form-control','placeholder' : 'ZIP'}),
           'contact1': TextInput(attrs={'class': 'required form-control','placeholder' : 'Contact 1'}),
           'contact2': TextInput(attrs={'class': 'required form-control','placeholder' : 'Contact 2'}),
           'email': TextInput(attrs={'class': 'required form-control','placeholder' : 'Email'}),
           
        }
        error_messages = {
            'name' : {
                'required' : _("Product field is required."),
            },
            'Address' : {
                'required' : _("Offer percentage field is required."),
            },
            'district' : {
                'required' : _("Start date field is required."),
            },
            'state' : {
                'required' : _("End Date field is required."),
            },
            'contact1' : {
                'required' : _("End Date field is required."),
            },
            'contact2' : {
                'required' : _("End Date field is required."),
            },
            'zipcode' : {
                'required' : _("End Date field is required."),
            },
        }

partners/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render,get_object_or_404
from django.http.response import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from partners.models import Partner
from partners.forms import PartnerForm
from django.contrib.auth.decorators import login_required
from main.decorators import check_mode,role_required
from main.functions import get_auto_id,generate_form_errors
import json
from users.forms import UserForm
from django.contrib.auth.models import User,Group
from dal import autocomplete
from django.db.models import Q
from main.functions import get_current_role


class PartnerAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        items = []
        current_role = get_current_role(self.request)
        if current_role == 'partner':
            items = Partner.objects.filter(is_deleted=False,user=self.request.user)
        else:
            items = Partner.objects.filter(is_deleted=False)
        if self.q:
            partners = items.filter(Q(name__istartswith=self.q))

    
        return partners


# Create your views here.
@check_mode
@login_required
@role_required(['partner','superadmin','administrator'])
def create_partner(request):

    if request.method == 'POST':
        form = PartnerForm(request.POST,request.FILES)
        
        if form.is_valid():


            data = form.save(commit=False)
            data.creator = request.user
            data.updator = request.user
            data.auto_id = get_auto_id(Partner)
            data.save() 

            response_data = {
                "status" : "true",
                "title" : "Successfully Created",
                "message" : "Partner(s) created successfully.",
                "redirect" : "true",
                "redirect_url" : reverse('partners:partners')
            }

        else:
            message = generate_form_errors(form, formset=False)
            response_data = {
                "status" : "false",
                "stable" : "true",
                "title" : "Form validation error",
                "message" : message
            }   
        return HttpResponse(json.dumps(response_data), content_type='application/javascript')
    else:
        form = PartnerForm()

        context = {
            "title": "Create Partner",
            "url": reverse('partners:create_partner'),
            "form" : form,
            "redirect" : True,

            "is_need_popup_box": True,
            "is_need_grid_system": True,
            "is_need_animations": True,
            "is_need_datetime_picker": True,
            "is_need_checkbox": True,
            "is_need_select_picker" : True,
            "is_need_formset" : True,
        }
        return render(request,'partners/entry.html',context)


@check_mode
@login_required
@role_required(['partner','superadmin','administrator'])
def edit_partner(request,pk):
    instance = get_object_or_404(Partner.objects.filter(pk=pk,is_deleted=False)) 
    
    if request.method == 'POST':
            
        response_data = {}
        form = PartnerForm(request.POST,request.FILES,instance=instance)
        
        if form.is_valid():  
            
            data = form.save(commit=False)
            data.updator = request.user
            data.date_updated = datetime.datetime.now()
            data.save()  


            response_data = {
                "status" : "true",
                "title" : "Successfully Updated",
                "message" : "Partner Successfully Updated.",
                "redirect" : "true",
                "redirect_url" : reverse('partners:Partner',kwargs={'pk':data.pk})
            }   
        else:
            message = generate_form_errors(form,formset=False)     
                    
            response_data = {
                "status" : "false",
                "stable" : "true",
                "title" : "Form validation error",
                "message" : message
            }  
            
        return HttpResponse(json.dumps(response_data), content_type='application/javascript')

    else: 

        form = PartnerForm(instance=instance)
        active_pincodes = instance.pincodes.all()
        
        context = {
            "form" : form,
            "title" : "Edit Partner : " + instance.name,
            "instance" : instance,
            "url" : reverse('partners:edit_partner',kwargs={'pk':instance.pk}),
            "redirect" : True,
            "active_pincodes" : active_pincodes,
            "cities" : cities,

            "is_need_popup_box": True,
            "is_need_grid_system": True,
            "is_need_animations": True,
            "is_need_datetime_picker": True,
            "is_need_checkbox": True,
            "is_need_select_picker" : True,
        }
        return render(request, 'partners/entry_partner.html', context)


@check_mode
@login_required
@role_required(['partner','superadmin','administrator'])
def partners(request):
    instances = Partner.objects.filter(is_deleted=False)
    title = "Partners"

    query = request.GET.get("q")
    if query:
        instances = instances.filter(Q(name__icontains=query))
        title = "partners - %s" % query

    context = {
        "instances": instances,
        'title': title,

        "is_need_popup_box": True,
        "is_need_grid_system": True,
        "is_need_animations": True,
        "is_need_datetime_picker": True,
        "is_need_checkbox": True
    }
    return render(request, 'partners/partners.html', context)


@check_mode
@login_required
@role_required(['partner','superadmin','administrator'])
def partner(request, pk):
    instance = get_object_or_404(Partner.objects.filter(is_deleted=False,pk=pk))
    title = "Partner"

    context = {
        "instance": instance,
        'title': title,

        "is_need_popup_box": True,
        "is_need_grid_system": True,
        "is_need_animations": True,
        "is_need_datetime_picker": True,
        "is_need_checkbox": True
    }
    return render(request, 'partners/partner.html', context)


@check_mode
@login_required
@role_required(['partner','superadmin','administrator'])
def delete_partner(request,pk):
    instance = get_object_or_404(Partner.objects.filter(pk=pk,is_deleted=False))
    
    Partner.objects.filter(pk=pk).update(is_deleted=True)
    
    response_data = {
        "status" : "true",
        "title" : "Successfully Deleted",
        "message" : "Partner Successfully Deleted.",
        "redirect" : "true",
        "redirect_url" : reverse('partners:partners')
    }
    return HttpResponse(json.dumps(response_data), content_type='application/javascript')


@check_mode
@login_required
@role_required(['partner','superadmin','administrator'])
def delete_selected_partners(request):
    pks = request.GET.get('pk')
    if pks:
        pks = pks[:-1]
        
        pks = pks.split(',')
        for pk in pks:      
            instance = get_object_or_404(Partner.objects.filter(pk=pk,is_deleted=False)) 
            Partner.objects.filter(pk=pk).update(is_deleted=True)
    
        response_data = {
            "status" : "true",
            "title" : "Successfully Deleted",
            "message" : "Selected Partner(s) Successfully Deleted.",
            "redirect" : "true",
            "redirect_url" : reverse('partners:partners')
        }
    else:
        response_data = {
            "status" : "false",
            "title" : "Nothing selected",
            "message" : "Please select some items first.",
        }
        
    return HttpResponse(json.dumps(response_data), content_type='application/javascript')


@login_required
@role_required(['superadmin','administrator'])
def make_user(request,pk): 
    partner = get_object_or_404(Partner.objects.filter(pk=pk))

    if request.method == "POST":
        form = UserForm(request.POST)
        response_data = {} 
        message = ""  
        data = []  
        emails = request.POST.get('email')
        email = str(emails)
        error = False
        if User.objects.filter(email=email).exists():
            error = True
            message += "This email already exists."
        if partner.user:
            error = True
            message += "This partner already has a user."
    
        if not error:
            if form.is_valid():    

                data = form.save(commit=False)
                data.email = email
                data.save()

                instance = data
                group = Group.objects.get(name="partner")
                instance.groups.add(group)

                partner.user=data
                partner.save()

                response_data = {
                    'status' : 'true',     
                    'title' : "User Created",       
                    'redirect' : 'true', 
                    'redirect_url' : reverse('partners:partner', kwargs = {'pk' : pk}),
                    'message' : "User Created Successfully"
                }
    
            else:
                error = True
                message = ''            
                message += generate_form_errors(form,formset=False)
                response_data = {
                    'status' : 'false',
                    'stable' : 'true',
                    'title' : "Form validation error",
                    'message' : message
                }
                
                message += generate_form_errors(form,formset=False)
    
        else:
            response_data = {
                'status' : 'false',     
                'title' : "Can't create this user",       
                'redirect' : 'true', 
                'redirect_url' : reverse('partners:make_user', kwargs={"pk":pk}),
                'message' : message
            }
    
        return HttpResponse(json.dumps(response_data), content_type='application/javascript')

    else: 
        form = UserForm(initial={'email':partner.email})

templates/partners/partner.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block content %}
    <div>
        <div class="row wrapper border-bottom white-bg p-h-xs">
        <div class="col-lg-12">
            <div class="row">
            <div class="col-lg-7">
                <h3>{{title}}</h3>
            </div>
            <div class="col-lg-5">
                <ul class="list-unstyled list-inline text-right m-r-md m-b-none m-t-sm">

                    <li class="no-margins">
                        <a  style="font-size:15px;" class="p-xxs" title="List"  href="{% url 'auditoriums:auditoriums' %}">
                            <i class="fa fa-list text-navy"></i>
                        </a>
                    </li>

                    <li class="no-margins">
                        <a  style="font-size:15px;" class="p-xxs" title="Edit Supplier" href="{% url 'auditoriums:edit_auditorium' pk=instance.pk %}">
                            <i class="fa fa-edit text-navy"></i>
                        </a>
                    </li>
                    
                    <li class="no-margins">
                        <a data-id="{{instance.pk}}" href="{% url 'auditoriums:delete_auditorium' pk=instance.pk %}" data-text="{{confirm_delete_message}}" data-title="Are you sure?"  class="action-button redirect">
                        <i class="fa fa-trash text-navy"></i>
                        </a>
                    </li>
                    
                    {% if not instance.user %}
                        <li class="no-margins">
                            <a  style="font-size:15px;" class="p-xxs" title="Create user" href="">
                                <i class="fa fa-plus-square-o text-navy"></i>
                            </a>
                        </li>
                    {% else %}
                        <li class="no-margins">
                            <a  style="font-size:15px;" class="p-xxs" title="Change permissions" href="">
                                <i class="fa fa-lock text-navy"></i>
                            </a>
                        </li>
                    {% endif %}

                    <li class="no-margins">
                        <a  style="font-size:15px;" class="p-xxs" title="Create Supplier" href="{% url 'auditoriums:create_auditorium' %}">
                            <i class="fa fa-plus text-navy"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        </div>
    </div>
    <div class="wrapper wrapper-content row animated fadeInRight">
        <div class="col-md-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Basic Details</h5>
                </div>
                <div>
                    <div class="ibox-content no-padding border-left-right">
                        {% if instance.photo %}
                            <img alt="image" class="img-responsive" src="{{instance.photo.url}}">
                        {% else %}
                            <img alt="image" class="img-responsive" src="{% static 'img/profile_big.jpg' %}">
                        {% endif %}
                    </div>
                    <div class="ibox-content profile-content">
                        <h4><strong>{{instance.name}}</strong></h4>
                        <p><i class="fa fa-map-marker"></i> {{instance.address}}/{{instance.location}}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Address Details</h5>
                </div>
                <div>
                    
                    <div class="ibox-content profile-content">
                        <div class="row m-t-lg">
                            <div class="col-md-12">
                                <span class="line"></span>
                                <h3><strong>Phone 1: </strong> {{instance.contact1}}</h3>
                            </div>
                            <div class="col-md-12">
                                <h3><strong>phone 2: </strong> {{instance.contact2}}</h3>
                            </div>
                            <div class="col-md-12">
                                <span class="line"></span>
                                <h3><strong>Email: </strong> {{instance.email}}</h3>
                            </div>
                            <div class="col-md-12">
                                <span class="line"></span>
                                <h3><strong>City: </strong> {{instance.city}}</h3>
                            </div>
                            <div class="col-md-12">
                                <span class="line"></span>
                                <h3><strong>District: </strong> {{instance.disicttr}}</h3>
                            </div>
                            <div class="col-md-12">
                                <span class="line"></span>
                                <h3><strong>State: </strong> {{instance.state}}</h3>
                            </div>
                            <div class="col-md-12">
                                <span class="line"></span>
                                <h3><strong>Zipcode: </strong> {{instance.zipcode}}</h3>
                            </div>
                            
                            
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
        
    </div>
{% endblock %}


{% block static %}
    {% load static %}
{% endblock %}

templates/partners/partners.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load main_template_tags %}
{% load tz %}
{% block content %}
    <div>
        <div class="row wrapper border-bottom white-bg p-h-xs">
            <div class="col-lg-12">
                <div class="row">
                    <div class="col-lg-5">
                        <h3>{{title}}</h3>
                    </div>
                    
                    <div class="col-lg-7">
                        <div class="row">
                            <div class="col-lg-7">
                                <form action="" class="form-inline">
                                    <div class="input-group">
                                        <input type="text" placeholder="Search" class="input-sm form-control" name="q"> 
                                        <span class="input-group-btn">
                                            <button type="submit" class="btn btn-sm btn-primary"> Go!</button>
                                        </span>
                                    </div>
                                </form>
                            </div>
                        </div>   
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
            {% if instances %}
                <div class="ibox float-e-margins">
                    <div class="ibox-content">
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Name</th>
                                        <th>Address</th>
                                        <th>District</th>
                                        <th>State</th>
                                        <th>Pincode</th>
                                        <th>Email</th>
                                        <th>Contact</th>
                                        <th width="90px" class="text-right">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% load el_pagination_tags %}
                                {% paginate 8 instances %}
                                {% for instance in instances %}
                                    <tr>
                                        <td><a href="{% url 'partners:partner' pk=instance.pk %}">{{instance.auto_id}}</a></td>
                                        <td>{{instance.name}}</td>
                                        <td>{{instance.address}}</td>
                                        <td>{{instance.district|default:"-"}}</td>
                                        <td>{{instance.state|default:"-"}}</td>
                                        <td>{{instance.zipcode}}</td>
                                        <td>{{instance.email}}</td>
                                        <td>{{instance.contact1}} / {{instance.contact1}}</td>
                                        <td class="text-right" width="90px">
                                            <a href="{% url 'partners:edit_partner' pk=instance.pk %}" class="m-r-xs"><i class="fa fa-pencil text-navy"></i></a>
                                            <a data-id="{{instance.pk}}" href="{% url 'partners:delete_partner' pk=instance.pk %}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" class="action-button remove run-function-after btn btn-white" data-function="change_after_delete"><i class="fa fa-trash text-navy"></i></a>
                                            {% if not instance.user %}
                                            <a href="{% url 'partners:make_user' pk=instance.pk %}" class="m-r-xs"><i class="fa fa-user text-navy"></i></a>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div> 
                <!--pagination -->
                <div class="bootgrid-footer container-fluid" id="data-table-selection-footer">
                    {% get_pages %}
                    <div class="row">
                        <div class="col-sm-6 text-left">
                            <div class="pagination">
                                {% show_pages %}
                            </div>
                        </div>
                        <div class="col-sm-6 infoBar text-right m-t-md">
                            <div class="infos">
                                Showing {{title}} <span class="current_page_index">{{ pages.current_start_index }}</span> - <span class="current_end_status">{{ pages.current_end_index }}</span> of <span class="total_count">{{ pages.total_count }}</span>
                            </div>
                        </div>
                    </div>
                </div>   
                <!--pagination-->
                {% else %}
                    {% include 'includes/not_found.html' %}
                {% endif %}   
            </div><!-- div.col-lg-12 -->

        </div><!-- div.row -->
    </div> <!-- div.wrapper -->
{% endblock %}

{% block filter_box %}
<div class="filter-box">
     <form method="get" action="">
        <div class="ibox">
            <div class="ibox-header p-xs">
                <h4 style="display: inline-block;">Filter <small></small></h4>
                <span class="back-button-poupup palette-Cyan bg white btn btn-default btn-icon-text waves-effect"><i class="fa fa-arrow-circle-o-left"></i> Back</span>
            </div>
            
            <div class="ibox-content">
                <div class="form-group">
                    <label>Query</label>
                    <input name="q" type="text" class="form-control" placeholder="Enter your query..." />
                </div>
                
                 <div class="m-t-20">
                    <button type="submit" class="btn btn-info waves-effect">Submit</button>
                </div>
            </div>
         </div>
     </form>
</div>
{% endblock %}


{% block static %}
    {% load static %}
{% endblock %}